version: '3.1'

services:

  mongo:
    image: mongo
    container_name: film-list
    ports:
      - "27017:27017"
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example